var workWindows = [
	{
		windowId: "tacklebox",
		title: "Tacklebox",
		year: "2019 - present",
		url: "https://tacklebox.company",
		displayUrl: "tacklebox.company",
		logoSrc: "img/logos/tacklebox.png",
		role: "Coding",
		client: "none",
		description: "<strong>Tacklebox</strong> is an Ottawa-based multimedia production company specializing in web and mobile development, graphic design, and video production.",
		screenshots: [
			"img/screenshots/tacklebox1.png",
			"img/screenshots/tacklebox2.jpg",
			"img/screenshots/tacklebox3.png",
		],
		iconTitle: "Tacklebox",
		iconSrc: "img/icons/tacklebox.png"
	},
	{
		windowId: "cartivoice",
		title: "carti voice",
		year: "2019",
		url: "https://cartivoice.com",
		displayUrl: "cartivoice.com",
		logoSrc: "img/logos/cartivoice.png",
		role: "Concept, design, coding",
		client: "none",
		description: "<strong>carti voice</strong> is a meme generator that takes user-input text and translates it into the unique typing style of rapper Playboi Carti.<p>I came up with the idea one day in March of 2019, and four days later, <a href=\"https://twitter.com/LScorrcho/status/1107341327182651394\" data-type=\"URL\" data-id=\"https://twitter.com/LScorrcho/status/1107341327182651394\" target=\"_blank\">the site was live.</a> It went viral immediately after release, with thousands of Carti fans using the site to create tweets and Instagram captions. The site still receives thousands of page views weekly.",
		screenshots: [
			"img/screenshots/cartivoice.png",
			"img/screenshots/cartivoice2.png",
			"img/screenshots/cartivoice3.png",
			"img/screenshots/cartivoice4.png"
		],
		iconTitle: "carti voice",
		iconSrc: "img/icons/cartivoice.png"
	},
	{
		windowId: "thisshowrules",
		title: "This Show Rules",
		year: "2019",
		url: "https://thisshowrules.com",
		displayUrl: "thisshowrules.com",
		logoSrc: "img/logos/thisshowrules.png",
		role: "Concept, design, coding",
		client: "none",
		description: "<strong>This Show Rules</strong> is a soundboard based on clips from <i>Time Crisis</i>, an Apple Music 1 radio show hosted by Vampire Weekend frontman Ezra Koenig & American painter Jake Longstreth. <p>Users can click on the different squares to play iconic \"drops\" from the show, including \"8 Minute Cape Cod\" and \"Corporate Food History,\" as well as classic quotes.",
		screenshots: [
			"img/screenshots/thisshowrules1.png",
			"img/screenshots/thisshowrules2.png",
		],
		iconTitle: "This Show<br>Rules",
		iconSrc: "img/icons/thisshowrules.png"
	},
	{
		windowId: "amco",
		title: "AMCO",
		year: "2021",
		url: "https://amcosounds.com",
		displayUrl: "amcosounds.com",
		logoSrc: "img/logos/amco.png",
		role: "Coding",
		client: "AMCO",
		description: "AMCO is a distribution, publishing and management company founded by the team behind the renowned independent music collective Awful Records, known for artists such as Father, Playboi Carti, Zack Fox, ABRA, Tommy Genesis, Faye Webster, and Danger Incorporated, amongst others.",
		screenshots: [
			"img/screenshots/amco1.jpg",
			"img/screenshots/amco2.jpg",
		],
		iconTitle: "AMCO",
		iconSrc: "img/icons/amco.png"
	},
	{
		windowId: "hoodbabysurf",
		title: "#HoodBabySurf",
		year: "2019",
		url: "https://apps.apple.com/us/app/hoodbabysurf/id1469347552",
		displayUrl: "Download (iOS App Store)",
		logoSrc: "img/logos/hoodbabysurf.png",
		role: "iOS development, distribution",
		client: "Alamo Records",
		description: "<strong>#HoodBabySurf</strong> is an iOS game in which the player controls rapper Lil Gotit as he surfs the seas saving mermaids and collecting powerups.<p>The game features a soundtrack comprised of Lil Gotit's biggest hits, and is often updated to promote his new album and single releases. An iMessage sticker pack with Lil Gotit-related illustrations is included with the app.",
		screenshots: [
			"img/screenshots/hoodbabysurf-1.png",
			"img/screenshots/hoodbabysurf-2.png",
			"img/screenshots/hoodbabysurf-3.png",
			"img/screenshots/hoodbabysurf-4.jpg",
		],
		iconTitle: "#HoodBabySurf",
		iconSrc: "img/icons/hoodbabysurf2.png"
	},
	{
		windowId: "yachtclub",
		title: "Yacht Club: Wave Runna",
		year: "2020",
		url: "https://apps.apple.com/ca/app/yacht-club-wave-runna/id1471445776",
		displayUrl: "Download (iOS App Store)",
		logoSrc: "img/logos/yachtclub.png",
		role: "iOS development, distribution",
		client: "300 Entertainment / YSL Records",
		description: "<strong>Yacht Club: Wave Runna</strong> is an iOS game in which the player controls rapper Strick and friends as they ride jetskis, doing stunts and collecting nitros to beat the clock and obtain the highest score possible.<p>The app was commissioned to promote Strick’s 2020 single \"Yacht Club\" featuring Young Thug and Ty Dolla $ign.",
		screenshots: [
			"img/screenshots/yachtclub1.jpg",
			"img/screenshots/yachtclub2.jpg",
			"img/screenshots/yachtclub3.jpg",
		],
		iconTitle: "Yacht Club:<br>Wave Runna",
		iconSrc: "img/icons/yachtclub.png"
	},
	{
		windowId: "trappedoncleveland",
		title: "Trapped On Cleveland",
		year: "2020",
		url: "https://apps.apple.com/us/app/trapped-on-cleveland/id1527010393",
		displayUrl: "Download (iOS App Store)",
		logoSrc: "img/logos/trappedoncleveland.png",
		role: "iOS development, distribution",
		client: "300 Entertainment / YSL Records",
		description: "<strong>Trapped On Cleveland</strong> is an iOS game inspired by <i>Friday the 13th</i> in which the player controls rapper Lil Keed as he fights off hordes of zombies using a chainsaws, shotguns, and dynamite.<p>The app was commisioned to promote Lil Keed's 2020 mixtape \"Trapped On Cleveland 3,\" and the game features songs from that mixtape as well as some of his other hits.",
		screenshots: [
			"img/screenshots/trappedoncleveland1.jpg",
			"img/screenshots/trappedoncleveland2.jpg",
			"img/screenshots/trappedoncleveland3.jpg",
			"img/screenshots/trappedoncleveland4.jpg",
		],
		iconTitle: "Trapped On<br>Cleveland",
		iconSrc: "img/icons/trappedoncleveland.png"
	},
	{
		windowId: "meetmeatthelondon",
		title: "#MeetMeAtTheLondon",
		year: "2019",
		url: "work/meetmeatthelondon/index.html",
		displayUrl: "meetmeatthelondon.com (Archive)",
		logoSrc: "img/logos/meetmeatthelondon.png",
		role: "Coding",
		client: "300 Entertainment / YSL Records",
		description: "<strong>#MeetMeAtTheLondon</strong> is a meme generator where users can upload a photo of their face and insert it into a cutout of Young Thug.<p>The site was commissioned as a digital activation to promote Young Thug’s 2019 single \"The London\" featuring Travis Scott & J. Cole, which peaked at #12 on the Billboard Hot 100 and is certified 3x Platinum.",
		screenshots: [
			"img/screenshots/meetmeatthelondon.jpg",
			"img/screenshots/meetmeatthelondon2.jpg",
		],
		iconTitle: "#MeetMeAt<br>TheLondon",
		iconSrc: "img/icons/meetmeatthelondon1.png"
	},
	// {
	// 	windowId: "numa",
	// 	title: "NUMA Architect",
	// 	year: "2020",
	// 	url: "xx",
	// 	displayUrl: "xx",
	// 	logoSrc: "img/logos/rodwavecontest.png",
	// 	role: "Coding, HTML5 animation",
	// 	client: "Ruriko Numazawa",
	// 	description: "<strong>NUMA Architect</strong> is the website for Ottawa-based architect Ruriko Numazawa. The site notably features an animated homepage, where over time, the site navigation and house blueprints fade in over a forest, culminating in the appearance of the final house.",
	// 	screenshots: [
	// 		"img/screenshots/rodwavecontest1.jpg",
	// 		"img/screenshots/rodwavecontest2.jpg",
	// 	],
	// 	iconTitle: "NUMA<br>Architect",
	// 	iconSrc: "img/icons/rags2riches.png"
	// },
	{
		windowId: "rags2riches",
		title: "Rags2Riches",
		year: "2020",
		url: "work/rags2riches/index.html",
		displayUrl: "rags-2-riches.com (Archive)",
		logoSrc: "img/logos/rags2riches.png",
		role: "Coding",
		client: "Alamo Records",
		description: "<strong>Rags2Riches</strong> is a meme generator where users can upload photos of themselves to create their own custom Rod Wave $100 bill, with their picture being the presidential portrait in the middle.<p>This digital activation was created to promote the deluxe edition of Rod Wave’s album Pray 4 Love. The site itself is inspired by Rod Wave’s viral TikTok song \"Rags2Riches.\"",
		screenshots: [
			"img/screenshots/rags2riches1.jpg",
		],
		iconTitle: "Rags2Riches",
		iconSrc: "img/icons/rags2riches.png"
	},
	{
		windowId: "rodwavecontest",
		title: "Rod Wave - Day 1 Contest",
		year: "2021",
		url: "work/rodwavecontest/index.html",
		displayUrl: "rodwavecontest.com (Archive)",
		logoSrc: "img/logos/rodwavecontest.png",
		role: "Coding, contest design",
		client: "Alamo Records / SoundCloud",
		description: "<strong>Rod Wave - Day 1 Contest</strong> was an online activation that rewarded Rod Wave's biggest fans in various cities with tickets to his 2021 SoulFly Tour. To enter, fans would submit a short voice memo explaining why they are Rod Wave's biggest fan.<p>This site featured the contest form as well as a SoundCloud player that played voice memos that fans had previously submitted.",
		screenshots: [
			"img/screenshots/rodwavecontest1.jpg",
			"img/screenshots/rodwavecontest2.jpg",
		],
		iconTitle: "Day 1 Contest",
		iconSrc: "img/icons/rags2riches.png"
	},
	{
		windowId: "greatishe",
		title: "Great Is He",
		year: "2023",
		url: "https://gihealbum.com",
		displayUrl: "gihealbum.com",
		logoSrc: "img/logos/greatishe.png",
		role: "Coding",
		client: "OVO Sound",
		description: "<strong>Great is He</strong> is a promotional website for Popcaan's 2023 album of the same name. The site features an image generator that allows fans to upload a photo that is then transformed to look like the Great Is He album cover. The site also contains streaming links, music videos, and upcoming tour dates.",
		screenshots: [
			"img/screenshots/greatishe1.jpg",
			"img/screenshots/greatishe2.jpg",
			"img/screenshots/greatishe3.jpg",
		],
		iconTitle: "Great Is He",
		iconSrc: "img/icons/greatishealt.png"
	},
	{
		windowId: "mixedemotions",
		title: "Mixed Emotions - The Journey",
		year: "2023",
		url: "https://mixedemotions.roywoods.com",
		displayUrl: "mixedemotions.roywoods.com",
		logoSrc: "img/logos/mixedemotions.png",
		role: "Coding",
		client: "OVO Sound",
		description: "<strong>Mixed Emotions - The Journey</strong> is a promotional website for Roy Woods' 2023 album <i>Mixed Emotions</i>. This experience takes the user on an audio \"journey\", allowing users to make choices that lead to unique outcomes, which include exclusive snippets from the new album as well as voice notes from Roy himself. <p>At the end of the experience, users can read and sign a guestbook with a message for Roy, as well as see more information on Mixed Emotions the album.",
		screenshots: [
			"img/screenshots/greatishe1.jpg",
		],
		iconTitle: "Mixed Emotions'",
		iconSrc: "img/icons/rags2riches.png"
	},
];
